<?php

namespace AppBundle\Repository;

/**
 * BenevoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BenevoleRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllRaidBene($user) {
      $qb = $this->createQueryBuilder('b')
    //  ->orderBy('o.id', 'ASC')
      ->select('b.idRaid')
      ->where("b.idUser=:id")->setParameter("id", $user->getId())
      ;

      return $qb->getQuery ()->getResult();
    }
}
