<?php

namespace AppBundle\Repository;

/**
 * OrganisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisateurRepository extends \Doctrine\ORM\EntityRepository
{

  public function findAllRaidOrga($user) {
      $qb = $this->createQueryBuilder('o')
    //  ->orderBy('o.id', 'ASC')
      ->select('o.idRaid')
      ->where("o.idUser=:id")->setParameter("id", $user->getId())
      ;
      
      return $qb->getQuery ()->getResult();
    }
}
