<?php

namespace AppBundle\Repository;

/**
 * RaidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaidRepository extends \Doctrine\ORM\EntityRepository
{
    function findRaidsOrganisateursByIdUser(int $id_user): array
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = "SELECT * FROM Raid r INNER JOIN Organisateur o WHERE o.idUser = :idUser AND r.id = o.idRaid";
        $stmt = $conn->prepare($sql);
        $stmt->execute(['idUser' => $id_user]);
        return $stmt->fetchAll();
    }

    function findRaidsBenevolesByIdUser(int $id_user): array
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = "SELECT * FROM Raid r INNER JOIN Benevole b WHERE b.idUser = :idUser AND r.id = b.idRaid";
        $stmt = $conn->prepare($sql);
        $stmt->execute(['idUser' => $id_user]);
        return $stmt->fetchAll();
    }

    function findAllRaids(): array
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = "SELECT * FROM Raid r";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
