<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RaidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaidRepository extends \Doctrine\ORM\EntityRepository
{

/*  public function findAllRaid($user) {
    $qb = $this->createQueryBuilder('r')
    ->orderBy('r.nom', 'ASC')

    ->where("r.auteur=:email")->setParameter("email", $user->getEmail())

    ;
    return $qb->getQuery ()->getResult();
  }*/
}
