<?php

namespace AppBundle\Repository;

/**
 * RaidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaidRepository extends \Doctrine\ORM\EntityRepository
{
}
