security:
    providers:
        webservice:
            id: AppBundle\Security\User\WebserviceUserProvider

    encoders:
        AppBundle\Entity\WebserviceUser: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: webservice
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: landing
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - app.webservice_authenticator